### ISSUE TITLE
postcss-nested-props breaks upon encountering :global or :local pseudo-selectors

### ISSUE THREAD

**Issue by Kovensky** [jedmao/postcss-nested-props#9] opened 2016-08-05 07:01 UTC
Note that I've encountered this in combination with sugarss, which encourages the use of this transform. css-modules uses the `:global` and `:local` pseudo-selectors to selectively disable/enable css-modules with the selectors nested within.

The following sugarss:

``` sass
:global .selector
  prop: value
  another-prop: another-value
```

Gets transformed into the following CSS:

``` css
:global .selector {
  prop: value;
  another-prop: another-value
}
```

The previous CSS, after running by postcss-nested-props, is transformed into the following invalid CSS, even though no nested props are present:

``` css
: global .selector;
-prop: value;
-another-prop: another-value
```

It seems to understand `:global` as being a nesting of "empty string" with the "global .selector" property name, which... makes very little sense.

Is this intended to support a corner case where the caller specifies a prop value _and_ nested props with the same prop declaration, without any whitespace? Perhaps it would be better to _require_ whitespace before such a construct, specifically to prevent the syntactic ambiguity with pseudo-selectors and pseudo-elements. A regexp whitelist will always be a moving target, and will mysteriously cause breakages every time a new one is used.

**Comment by jedmao** [comment] 2016-08-29 07:11
@Kovensky, I've [added a commit](https://github.com/jedmao/postcss-nested-props/pull/8/commits/6c1e3d8fc3c91f60220f1555b9c753ee975f744d) to https://github.com/jedmao/postcss-nested-props/pull/8 that should be published in a week or two, whenever TypeScript 2.0.1 is officially released (should be soon). I'll be unavailable this weekend, however, as I'll be flying to China during that time.

**Comment by tomxtobin** [comment] 2017-01-05 20:56
Any chance this fix can get published? I'd like to use this plugin, but I'm using CSS Modules.

**Comment by jedmao** [comment] 2017-01-09 17:06
Gotta' wait a few more days for https://github.com/postcss/postcss/pull/950. Sorry for the long wait. I lost track of this one somehow.

**Comment by tomxtobin** [comment] 2017-01-09 17:15
No worries. Thanks!

**Comment by jedmao** [comment] 2017-01-20 08:05
@tomxtobin can you give v1.1.5 a try?

**Comment by tomxtobin** [comment] 2017-01-25 22:17
Finally got a chance to test it out. It's still not working, unfortunately.

I'm getting invalid CSS that's a little different than before: `: global(.some-class-name)`.

Instead, the final CSS output should be `.some-class-name`.

**Comment by jedmao** [comment] 2017-01-25 22:20
Do [these two tests](https://github.com/jedmao/postcss-nested-props/blob/634e74d1e4919e479be39dd7b023a240213c1f22/test/plugin.ts#L44-L56) not represent the issue you have having? If not, can you write a failing test for me in the form of a PR?

**Comment by tomxtobin** [comment] 2017-01-25 22:30
It needs to preserve all of these possible forms, in these contexts:
```css
.zeroOrMoreSelectors :global .oneOrMoreSelectors
.zeroOrMoreSelectors :local .oneOrMoreSelectors
.zeroOrMoreSelectors :global(.oneOrMoreSelectors) .zeroOrMoreSelectors
.zeroOrMoreSelectors :local(.oneOrMoreSelectors) .zeroOrMoreSelectors
```
But sure, I can write a PR when I have a chance.

**Comment by jedmao** [comment] 2017-01-25 23:12
Excellent, please do. I think it would add clarity to the exact scenarios in question. Also, if/when you do write the failing tests, try to keep it as simple as possible with `foo`, `bar`, `baz` and the like.

**Comment by jedmao** [comment] 2017-02-22 20:38
@tomxtobin I've updated the dependencies, gutted gulp, introduced ava. It should be a bit easier for you to write tests now.

**Comment by jedmao** [comment] 2017-03-17 06:07
@Kovensky, I've written a test, but it passes, so I can't reproduce your issue. Here's my test:
```js
test('preserves :global selector rule', scenario(
	`:global .a{b:c;d:e;}`,
	`:global .a{b:c;d:e;}`
));
```
Closing until I can get a breaking test. Otherwise, it might just be the order in which you're loading your PostCSS plugins.

**Closed by jedmao** 2017-03-17 06:07 UTC
Labels: bug
