### ISSUE TITLE
Plugin throws Error in >=1.0.2

### ISSUE THREAD

**Issue by danieldiekmeier** [jedmao/postcss-nested-props#5] opened 2016-02-04 13:52 UTC
When I use the plugin locally on my Mac (OSX 10.11.1 with Node 5.0.0), it works great!

If I run it on my Continuous Integration Platform (Ubuntu, Node 4.2), it fails while shouting

```
Error: [object Object] is not a PostCSS plugin
```

When I force the `package.json` to use 1.0.0, it works great, but 1.0.2 and 1.1.0 have this error.

**Comment by jedmao** [comment] 2016-02-04 16:36
My CI works fine on Node 5.4.0. It seems the version of Node might have something to do with it? I'm guessing you're stuck on Node 4.2 for a while?

**Comment by danieldiekmeier** [comment] 2016-02-05 10:04
4.2 is still the LTS version, so we'll probably be on that for a while. We can just use 1.0.0, it's not an issue. I just thought you should know!

**Comment by jedmao** [comment] 2016-02-05 15:43
@danieldiekmeier I've added Node 4.2 and 5.5 to PR #6 and it looks like they are both passing in Travis right now. I think [this line](https://github.com/jedmao/postcss-nested-props/blob/master/test/plugin.ts#L86) would be the most interesting to you, considering it's the line that loads the plugin for all of the tests. Since this is working, I'm afraid I'm unable to reproduce the issue at hand.

Perhaps if you could provide a failing test I could look into it deeper?

**Comment by danieldiekmeier** [comment] 2016-02-05 20:18
I actually left my job at the company where we had this problem yesterday, so I don't need this fixed anymore. I just thought that if there was an obvious change since 1.0.0 that could have caused it, you could have fixed it. But as it stands now, it seems fine for me. Thanks for your time!

**Comment by jedmao** [comment] 2016-02-05 20:46
I think the only thing that changed is the version of Babel that transpiled the code, but I'm fine closing this until someone else experiences the same problem.

**Closed by jedmao** 2016-02-05 20:46 UTC

**Comment by gaintsev** [comment] 2016-03-07 01:01
Hi! Thanks for the great module! I think I have the same problem:

`Error: [object Object] is not a PostCSS plugin`

Here is the full error output — [gist](https://gist.github.com/gaintsev/0cab8d5fc6d5f5b81ecb) and here my [gulpfile.js](https://gist.github.com/gaintsev/06f820de7007a1adabeb) I have everything worked fine with version 1.0.0. But it seems the problem is in the dependencies. Because now, when I try again to use version 1.0.0, I get the same error. My Node version 5.7.0.

**Comment by jedmao** [comment] 2016-03-07 05:06
@gaintsev, can you provide a failing test in the form of a PR? Because I can't repro.

**Comment by gaintsev** [comment] 2016-03-07 23:22
We together with my colleague did simple project here — https://github.com/gaintsev/postcss-nested-props-test We determined that the 1.0.0 version works fine. But the latest version causes an error. I hope this will help solve the problem.

**Comment by jedmao** [comment] 2016-03-09 06:03
I'm pretty sure `require('postcss-nested-props').default` will fix the issue for now, but I need to figure out why the build process is making it behave this way.

**Comment by gaintsev** [comment] 2016-03-09 13:19
`require('postcss-nested-props').default`

Yes. It works. )

**Comment by aviemet** [comment] 2016-06-02 17:34
Maybe you could add this to the Readme, I had this issue on Node v5.10.1, adding .default fixed it for me too. (I'm using webpack)

**Comment by jedmao** [comment] 2016-06-02 21:25
This should be fixed in v1.1.1 (published). There is a PR, but it's failing until postcss is updated.
